/**
 * Enum containing all environment variable keys
 * This provides type safety when accessing environment variables
 */
export enum EnvConstants {
  // API Documentation
  SWAGGER_TITLE = 'SWAGGER_TITLE',
  SWAGGER_DESCRIPTION = 'SWAGGER_DESCRIPTION',
  SWAGGER_VERSION = 'SWAGGER_VERSION',
  SWAGGER_DOCUMENT_SUFFIX = 'SWAGGER_DOCUMENT_SUFFIX',

  // Server
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  API_PREFIX = 'API_PREFIX',
  HOST = 'HOST',

  // JWT
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',

  // Swagger
  SWAGGER_ENABLED = 'SWAGGER_ENABLED',

  // Cors
  CORS_ENABLED = 'CORS_ENABLED',
  CORS_ORIGIN = 'CORS_ORIGIN',
  
  // Throttler (Rate Limiting)
  THROTTLER_TTL = 'THROTTLER_TTL',
  THROTTLER_LIMIT = 'THROTTLER_LIMIT',
  THROTTLER_ENABLED = 'THROTTLER_ENABLED',
  THROTTLER_SKIP_IF_EMPTY = 'THROTTLER_SKIP_IF_EMPTY',
  THROTTLER_STORAGE_TTL = 'THROTTLER_STORAGE_TTL',
  
  // API Versioning
  API_VERSION = 'API_VERSION',
  API_SUPPORTED_VERSIONS = 'API_SUPPORTED_VERSIONS',
  API_DEPRECATED_VERSIONS = 'API_DEPRECATED_VERSIONS',
  API_VERSIONING_TYPE = 'API_VERSIONING_TYPE',
  API_VERSIONING_HEADER = 'API_VERSIONING_HEADER',
  API_VERSIONING_ENABLED = 'API_VERSIONING_ENABLED',
} 